# https://circleci.com/docs/2.0/

version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10-stretch

    working_directory: /go/src/github.com/percolate/charlatan

    steps:
      - checkout
      - run:
          shell: /bin/bash
          name: go fmt
          command: |
            ! gofmt -l $(find . -path ./vendor -prune -o  -type f -name '*.go' -print) 2>&1 | read
      - run: go vet
      - run: make test
      - run: sbin/codecov -s build/coverage/

  mdl:
    docker:
      - image: prclt/cci-mdl:1.0.0
    steps:
      - checkout
      - run:
          name: Validate Markdown
          command: |
            mdl -r ~MD010 $(find . -path ./vendor -prune -o -type f -name '*.md' -print)

  release:
    docker:
      - image: prclt/cci-release:1.0.2
    steps:
      - checkout
      - deploy:
          name: Deploy to GitHub Releases
          environment:
            GITHUB_TOKEN: ${GITHUB_OAUTH_TOKEN}
          command: |
            ci-make-release $(cat VERSION.txt)

workflows:
  version: 2
  build_release:
    jobs:
      - mdl
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
